name: image_classification_1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.1.3
  - matplotlib=3.10.8
  - scikit-learn=1.8.0
  - seaborn=0.13.2
  - pandas=2.2.3            
  - pillow=11.0.0
  - pip
  - pip:
      - tensorflow==2.19.0  
      - opencv-python==4.10.0.84